# Этап сборки
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Этап запуска
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx-internal.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
