name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Run tests
        working-directory: ./client
        run: npm run test
        
      - name: Build frontend
        working-directory: ./client
        run: npm run build
        
      - name: Deploy to web server
        run: |
          # Create directory if it doesn't exist
          # sudo mkdir -p /var/www/amlacademy.kz
          
          # Remove old files
          rm -rf /var/www/amlacademy.kz/*
          
          # Copy build files to Nginx serve directory
          cp -r client/dist/* /var/www/amlacademy.kz/
          
          # Set proper permissions
          # sudo chown -R www-data:www-data /var/www/amlacademy.kz/
          # sudo chmod -R 755 /var/www/amlacademy.kz/
          
      - name: Remove Docker services
        run: |
          # Remove the Docker service if it exists
          if docker stack ls | grep -q "afm-academy"; then
            echo "Removing Docker stack services..."
            docker stack rm afm-academy
            # Wait for services to be removed
            sleep 10
          fi
          
      - name: Cleanup Docker resources
        run: |
          # Remove unused Docker images to free up space
          echo "Cleaning up unused Docker images..."
          docker image prune -f --filter "dangling=true"
          
          # Optional: Remove specific images related to this project
          if docker images | grep -q "localhost/afm-academy-frontend"; then
            echo "Removing old frontend Docker images..."
            docker rmi $(docker images --filter=reference="localhost/afm-academy-frontend:*" -q) || true
          fi